### ISSUE TITLE
关于追踪错误

### ISSUE THREAD

**Issue by KeterHY** [Kyomotoi/Project-ATRI-Console#1]
![image](https://user-images.githubusercontent.com/115984744/196138728-7670ac87-abe8-4b2f-ac4f-7c450e49252b.png)
ATRI | 10-17 16:59:35 | ERROR nonebot >> Running Matcher(type='message', module=控制台) failed.
Traceback (most recent call last):

  File "D:\ATRI\main.py", line 9, in <module>
    ATRI.run()
    │    └ <function run at 0x00000238D69D12D0>
    └ <module 'ATRI' from 'D:\\ATRI\\ATRI\\__init__.py'>

  File "D:\ATRI\ATRI\__init__.py", line 36, in run
    nonebot.run(log_level=log_level)
    │       │             └ 'warning'
    │       └ <function run at 0x00000238D6764EE0>
    └ <module 'nonebot' from 'C:\\Users\\Keter\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\atri-DJSBjSfB-py3.10\\lib\\site-packa...

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'log_level': 'warning'}
    │                 └ ()
    └ <function get_driver at 0x00000238D3B9F6D0>

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x00000238D7302320>
    └ <module 'uvicorn' from 'C:\\Users\\Keter\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\atri-DJSBjSfB-py3.10\\lib\\site-packa...

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
    │      └ <function Server.run at 0x00000238D73024D0>
    └ <uvicorn.server.Server object at 0x00000238FAA59FC0>

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x00000238D7302560>
           │       │   └ <uvicorn.server.Server object at 0x00000238FAA59FC0>
           │       └ <function run at 0x00000238D5896050>
           └ <module 'asyncio' from 'C:\\Users\\Keter\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Keter\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x00000238DC23B530>
           │    └ <function BaseEventLoop.run_until_complete at 0x00000238D5897A30>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Keter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000238D595AEF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Keter\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Keter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000238D589D510>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Keter\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000238D5834B80>
    └ <Handle Task.task_wakeup(<_GatheringFu...673747), 'N']>)>

  File "C:\Users\Keter\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...673747), 'N']>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...673747), 'N']>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...673747), 'N']>)>

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function Matcher.got.<locals>._key_getter at 0x00000238DC112320>: <Task finished name='Task-2816' coro=<Matcher.got.<locals...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x00000238FBEB9240>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │            │        │    └ PrivateMessageEvent(time=1665997175, self_id=2168673747, post_type='message', sub_type='friend', user_id=1368437200, message_...
          │            │        └ Bot(type='OneBot V11', self_id='2168673747')
          │            └ Matcher(type='message', module=控制台)
          └ <function _run_matcher at 0x00000238D69017E0>

> File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function Matcher.got.<locals>._key_getter at 0x00000238DC112320>: <Task finished name='Task-2816' coro=<Matcher.got.<locals...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x00000238FBEB9240>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │       │   │    └ PrivateMessageEvent(time=1665997175, self_id=2168673747, post_type='message', sub_type='friend', user_id=1368437200, message_...
          │       │   └ Bot(type='OneBot V11', self_id='2168673747')
          │       └ <function Matcher.run at 0x00000238D67676D0>
          └ Matcher(type='message', module=控制台)

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function Matcher.got.<locals>._key_getter at 0x00000238DC112320>: <Task finished name='Task-2816' coro=<Matcher.got.<locals...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x00000238FBEB9240>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │    │          │    └ PrivateMessageEvent(time=1665997175, self_id=2168673747, post_type='message', sub_type='friend', user_id=1368437200, message_...
          │    │          └ Bot(type='OneBot V11', self_id='2168673747')
          │    └ <function Matcher.simple_run at 0x00000238D6767640>
          └ Matcher(type='message', module=控制台)

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
          └ Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))

  File "C:\Users\Keter\AppData\Local\pypoetry\Cache\virtualenvs\atri-DJSBjSfB-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'event': PrivateMessageEvent(time=1665997175, self_id=2168673747, post_type='message', sub_type='friend', user_id=1368437200...
                 │    │             │         │    │    └ <function _ at 0x00000238DC112200>
                 │    │             │         │    └ Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x00000238D3C03490>

  File "D:\ATRI\ATRI\plugins\console\__init__.py", line 45, in _
    data = json.loads(__AUTH_FILE_PATH.read_bytes())["data"]
           │    │     │                └ <function Path.read_bytes at 0x00000238D3BADFC0>
           │    │     └ WindowsPath('data/plugins/console/data.json')
           │    └ <function loads at 0x00000238D5A0E830>
           └ <module 'json' from 'C:\\Users\\Keter\\AppData\\Local\\Programs\\Python\\Python310\\lib\\json\\__init__.py'>

KeyError: 'data'
ATRI | 10-17 16:59:35 | ERROR ATRI >> Error Track ID: mBohEjZA
ATRI | 10-17 17:08:13 | INFO status >> 开始检查资源消耗...
ATRI | 10-17 17:08:15 | INFO status >> 资源消耗正常

**Comment by Kyomotoi** [comment]
请在项目根目录下键入 `git log` 并截图最近的几条

**Comment by Kyomotoi** [comment]
最近更新已修复该问题
